word_list = {
    "easy": [
    'cat', 'dog', 'sun', 'moon', 'star', 'fish', 'tree', 'bird', 'book', 'ball',
'run', 'jump', 'rain', 'fire', 'wind', 'snow', 'ice', 'leaf', 'hand', 'foot',
'nose', 'ear', 'eye', 'lip', 'arm', 'leg', 'hat', 'cup', 'bed', 'pen', 'cup',
'cake', 'door', 'bell', 'key', 'lock', 'ship', 'car', 'bus', 'bike', 'bird',
'frog', 'duck', 'swim', 'sing', 'talk', 'walk', 'fall', 'play', 'read', 'run',
'fly', 'work', 'jump', 'cook', 'draw', 'spin', 'fold', 'milk', 'open', 'shut',
'push', 'pull', 'yell', 'kick', 'clap', 'snap', 'snap', 'spin', 'skip', 'stop',
'wait', 'wave', 'swim', 'toss', 'turn', 'wash', 'wrap', 'grab', 'drop', 'grab',
'take', 'give', 'pick', 'skip', 'kick', 'bake', 'melt', 'sing', 'dance', 'draw',
'skip', 'swim', 'wave', 'wash', 'play', 'read', 'cook', 'work', 'spin', 'walk',
'jump', 'stop', 'snap', 'spin', 'skip', 'fall', 'yell', 'clap', 'draw', 'talk',
'run', 'fly', 'fish', 'bell', 'cake', 'door', 'duck', 'fire', 'moon', 'ship',
'star', 'wind', 'leaf', 'fish', 'ball', 'book', 'bird', 'tree', 'rain', 'blue',
'hand', 'foot', 'nose', 'ear', 'eye', 'lip', 'arm', 'leg', 'hat', 'cup', 'bed',
'pen', 'cup', 'cake', 'door', 'bell', 'key', 'lock', 'ship', 'car', 'bus', 'bike',
'bird', 'frog', 'duck', 'swim', 'sing', 'talk', 'walk', 'fall', 'play', 'read',
'run', 'fly', 'work', 'jump', 'cook', 'draw', 'spin', 'fold', 'milk', 'open',
'shut', 'push', 'pull', 'yell', 'kick', 'clap', 'snap', 'snap', 'spin', 'skip',
'stop', 'wait', 'wave', 'swim', 'toss', 'turn', 'wash', 'wrap', 'grab', 'drop',
'grab', 'take', 'give', 'pick', 'skip', 'kick', 'bake', 'melt', 'sing', 'dance',
'draw', 'skip', 'swim', 'wave', 'wash', 'play', 'read', 'cook', 'work', 'spin',
'walk', 'jump', 'stop', 'snap', 'spin', 'skip', 'fall', 'yell', 'clap', 'draw',
'talk', 'run', 'fly', 'fish', 'bell', 'cake', 'door', 'duck', 'fire', 'moon',
'ship', 'star', 'wind', 'leaf'
],
    "hard": [
    'cat', 'dog', 'sun', 'moon', 'star', 'fish', 'tree', 'bird', 'book', 'ball',
'run', 'jump', 'rain', 'fire', 'wind', 'snow', 'ice', 'leaf', 'hand', 'foot',
'nose', 'ear', 'eye', 'lip', 'arm', 'leg', 'hat', 'cup', 'bed', 'pen', 'cup',
'cake', 'door', 'bell', 'key', 'lock', 'ship', 'car', 'bus', 'bike', 'bird',
'frog', 'duck', 'swim', 'sing', 'talk', 'walk', 'fall', 'play', 'read', 'run',
'fly', 'work', 'jump', 'cook', 'draw', 'spin', 'fold', 'milk', 'open', 'shut',
'push', 'pull', 'yell', 'kick', 'clap', 'snap', 'snap', 'spin', 'skip', 'stop',
'wait', 'wave', 'swim', 'toss', 'turn', 'wash', 'wrap', 'grab', 'drop', 'grab',
'take', 'give', 'pick', 'skip', 'kick', 'bake', 'melt', 'sing', 'dance', 'draw',
'skip', 'swim', 'wave', 'wash', 'play', 'read', 'cook', 'work', 'spin', 'walk',
'jump', 'stop', 'snap', 'spin', 'skip', 'fall', 'yell', 'clap', 'draw', 'talk',
'run', 'fly', 'fish', 'bell', 'cake', 'door', 'duck', 'fire', 'moon', 'ship',
'star', 'wind', 'leaf', 'fish', 'ball', 'book', 'bird', 'tree', 'rain', 'blue',
'hand', 'foot', 'nose', 'ear', 'eye', 'lip', 'arm', 'leg', 'hat', 'cup', 'bed',
'pen', 'cup', 'cake', 'door', 'bell', 'key', 'lock', 'ship', 'car', 'bus', 'bike',
'bird', 'frog', 'duck', 'swim', 'sing', 'talk', 'walk', 'fall', 'play', 'read',
'run', 'fly', 'work', 'jump', 'cook', 'draw', 'spin', 'fold', 'milk', 'open',
'shut', 'push', 'pull', 'yell', 'kick', 'clap', 'snap', 'snap', 'spin', 'skip',
'stop', 'wait', 'wave', 'swim', 'toss', 'turn', 'wash', 'wrap', 'grab', 'drop',
'grab', 'take', 'give', 'pick', 'skip', 'kick', 'bake', 'melt', 'sing', 'dance',
'draw', 'skip', 'swim', 'wave', 'wash', 'play', 'read', 'cook', 'work', 'spin',
'walk', 'jump', 'stop', 'snap', 'spin', 'skip', 'fall', 'yell', 'clap', 'draw',
'talk', 'run', 'fly', 'fish', 'bell', 'cake', 'door', 'duck', 'fire', 'moon',
'ship', 'star', 'wind', 'leaf','jacket', 'rocket', 'banana', 'purple', 'orange', 'turtle', 'guitar', 'pencil', 'rabbit', 'magnet',
'eleven', 'twelve', 'thirty', 'fifty', 'apple', 'happy', 'smile', 'dream', 'world', 'cloud',
'flower', 'music', 'earth', 'chair', 'table', 'phone', 'light', 'water', 'drink', 'sweet',
'black', 'white', 'green', 'brown', 'bread', 'pizza', 'watch', 'house', 'heart', 'paper',
'glass', 'fruit', 'money', 'shirt', 'shoe', 'sock', 'book', 'pen', 'bag', 'ring',
'king', 'queen', 'lion', 'tiger', 'bear', 'wolf', 'tree', 'leaf', 'star', 'moon',
'sun', 'fire', 'snow', 'rain', 'wind', 'ship', 'fish', 'bird', 'duck', 'swim',
'sing', 'jump', 'run', 'walk', 'fall', 'play', 'read', 'draw', 'cook', 'work',
'fly', 'spin', 'fold', 'open', 'shut', 'push', 'pull', 'yell', 'kick', 'clap',
'snap', 'wait', 'wave', 'toss', 'turn', 'wash', 'wrap', 'grab', 'take', 'give',
'pick', 'stop', 'talk', 'blue', 'pink', 'gold', 'gray', 'lamp', 'silk', 'kite',
'skate', 'ball', 'door', 'bell', 'bike', 'frog', 'snake', 'star', 'leaf', 'milk',
'soup', 'soap', 'ring', 'cake', 'bird', 'bear', 'deer', 'puma', 'seal', 'puff'
]
}
